services:
  - type: web
    name: orchid-continuum
    env: python
    plan: free

    buildCommand: |
      apt-get update && apt-get install -y \
        build-essential \
        libpq-dev \
        lib
